# Generated by Django 2.0.6 on 2021-09-30 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('pk_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=25)),
                ('raza', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('pk_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('imagen', models.URLField(default='https://cdn.euroinnova.edu.es/img/subidasEditor/11-1596082251.jpg', max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='veterinaria',
            fields=[
                ('pk_Veterinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.TextField()),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='fk_servicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.servicios'),
        ),
    ]
